### ISSUE TITLE
Misspelling of "Silixa"

### ISSUE THREAD

**Issue by BSchilperoort** [mdomanski-usgs/DTSGUI#1]
The name of the import functions of the Silixa files is misspelled. Should be "Silixa", not "Salixa".

**Comment by mdomanski-usgs** [comment]
Corrected in [corrected silixa spelling error](https://github.com/mdomanski-usgs/DTSGUI/commit/833d5bdb70459c5bc0099cea7b2274552dc7d653).

Thanks
